
CREATE PROCEDURE [dbo].[insertServiceReport] @title         NVARCHAR(50), 
                                            @reportmapid   NVARCHAR(50), 
                                            @reportid      NVARCHAR(50), 
                                            @projectno     NVARCHAR(50), 
                                            @refjob        NVARCHAR(50), 
                                            @pm            NVARCHAR(50), 
                                            @customer      NVARCHAR(50), 
                                            @planloc       NVARCHAR(max), 
                                            @contactname   NVARCHAR(50), 
                                            @authorizedby  NVARCHAR(50), 
                                            @equipment     NVARCHAR(150), 
                                            @techname      NVARCHAR(50), 
                                            @datecreated   NVARCHAR(50), 
                                            @futheractions NVARCHAR(max), 
                                            @custcomments  NVARCHAR(max), 
                                            @custrep       NVARCHAR(50), 
                                            @custemail     NVARCHAR(50), 
                                            @custcontact   NVARCHAR(50), 
                                            @published     NVARCHAR(50), 
                                            @signed        NVARCHAR(50), 
                                            @uploadedby    NVARCHAR(50), 
                                            @spare1        NVARCHAR(50), 
                                            @spare2        NVARCHAR(50), 
                                            @spare3        NVARCHAR(50), 
                                            @spare4        NVARCHAR(50), 
                                            @spare5        NVARCHAR(50) 
AS 
    INSERT INTO [dbo].[spservicereports] 
                ([title], 
                 [reportmapid], 
                 [report_id], 
                 [projectno], 
                 [refjob], 
                 [projectmanager], 
                 customer, 
                 planloc, 
                 contactname, 
                 authorizedby, 
                 equipment, 
                 techname, 
                 datecreated, 
                 furtheractions, 
                 custcomments, 
                 custrep, 
                 custemail, 
                 custcontact, 
                 published, 
                 signed, 
                 uploadedby, 
                 spare1, 
                 spare2, 
                 spare3, 
                 spare4, 
                 spare5) 
    VALUES      (@title, 
                 @reportmapid, 
                 @reportid, 
                 @projectno, 
                 @refjob, 
                 @pm, 
                 @customer, 
                 @planloc, 
                 @contactname, 
                 @authorizedby, 
                 @equipment, 
                 @techname, 
                 @datecreated, 
                 @futheractions, 
                 @custcomments, 
                 @custrep, 
                 @custemail, 
                 @custcontact, 
                 @published, 
                 @signed, 
                 @uploadedby, 
                 @spare1, 
                 @spare2, 
                 @spare3, 
                 @spare4, 
                 @spare5) 