CREATE TABLE [dbo].[ECR] (
    [ECRNo]          INT           NOT NULL,
    [JobNo]          VARCHAR (10)  NULL,
    [JobName]        VARCHAR (250) NULL,
    [SANo]           VARCHAR (10)  NULL,
    [SAName]         VARCHAR (250) NULL,
    [PartNo]         VARCHAR (250) NULL,
    [ProjectManager] VARCHAR (50)  NULL,
    [Description]    VARCHAR (MAX) NULL,
    [Comments]       VARCHAR (MAX) NULL,
    [Status]         VARCHAR (50)  NULL,
    [CreatedBy]      VARCHAR (30)  NULL,
    [DateCreated]    DATETIME      NULL,
    [RequestedBy]    VARCHAR (50)  NULL,
    [DateLastSaved]  DATETIME      NULL,
    [LastSavedBy]    VARCHAR (50)  NULL,
    [Department]     VARCHAR (50)  NULL,
    [Submitted]      INT           CONSTRAINT [DF_ECRBase_Submitted] DEFAULT ((0)) NOT NULL,
    [Submittedby]    VARCHAR (50)  NULL,
    [SubmittedOn]    DATETIME      NULL,
    [SupervisorId]   INT           CONSTRAINT [DF_ECR_SupervisorId] DEFAULT ((0)) NOT NULL,
    [SupApproval]    INT           CONSTRAINT [DF_ECRBase_SupApproval] DEFAULT ((0)) NOT NULL,
    [SupApprovalBy]  VARCHAR (50)  NULL,
    [SupApprovedOn]  DATETIME      NULL,
    [SubmitToId]     INT           CONSTRAINT [DF_ECR_SubmitToId] DEFAULT ((0)) NOT NULL,
    [Approved]       INT           CONSTRAINT [DF_ECRBase_Approved] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]     VARCHAR (50)  NULL,
    [ApprovedOn]     DATETIME      NULL,
    [AssignedTo]     INT           CONSTRAINT [DF_ECR_AssignedTo] DEFAULT ((0)) NOT NULL,
    [Completed]      INT           CONSTRAINT [DF_ECRBase_Completed] DEFAULT ((0)) NOT NULL,
    [CompletedBy]    VARCHAR (50)  NULL,
    [CompletedOn]    DATETIME      NULL,
    CONSTRAINT [PK_ECRBase] PRIMARY KEY CLUSTERED ([ECRNo] ASC)
);

