CREATE TABLE [dbo].[PurchaseReqBase] (
    [ReqNumber]     INT           NOT NULL,
    [JobNumber]     VARCHAR (50)  NOT NULL,
    [RequestedBy]   VARCHAR (50)  NULL,
    [DateCreated]   DATETIME      NULL,
    [LastSavedBy]   VARCHAR (50)  NULL,
    [DateLastSaved] DATETIME      NULL,
    [SubAssyNumber] VARCHAR (50)  NULL,
    [Notes]         VARCHAR (MAX) NULL,
    [DateRequired]  DATE          NULL,
    [Validate]      INT           NULL,
    [DateValidated] DATETIME      NULL,
    [Approved]      INT           NULL,
    [Approvedby]    VARCHAR (50)  NULL,
    [DateApproved]  DATETIME      NULL,
    [Total]         MONEY         NULL,
    [SupervisorId]  INT           NULL,
    [HApproval]     INT           NULL,
    [Happroved]     INT           NULL,
    [HApprovedBy]   VARCHAR (50)  NULL,
    [HDateApproved] DATETIME      NULL,
    [PApproval]     INT           NULL,
    [Papproved]     INT           NULL,
    [PDateApproved] DATETIME      NULL,
    [PApprovedBy]   VARCHAR (50)  NULL,
    [PONumber]      VARCHAR (50)  NULL,
    [PODate]        DATE          NULL,
    CONSTRAINT [PK_PurchaseReqBase] PRIMARY KEY CLUSTERED ([ReqNumber] ASC)
);

