CREATE TABLE [dbo].[RP_Base] (
    [Id]            INT           IDENTITY (1, 1) NOT NULL,
    [RelNo]         INT           NOT NULL,
    [Job]           INT           NULL,
    [SubAssy]       VARCHAR (25)  NULL,
    [PckgQty]       INT           CONSTRAINT [DF_RP_Base_PckgQty] DEFAULT ((1)) NOT NULL,
    [IsSubmitted]   INT           CONSTRAINT [DF_RP_Base_IsSubmitted] DEFAULT ((0)) NOT NULL,
    [SubmittedTo]   INT           CONSTRAINT [DF_RP_Base_SubmittedTo] DEFAULT ((0)) NOT NULL,
    [SubmittedOn]   DATETIME      NULL,
    [IsChecked]     INT           CONSTRAINT [DF_RP_Base_IsChecked] DEFAULT ((0)) NOT NULL,
    [CheckedBy]     VARCHAR (50)  NULL,
    [CheckedOn]     DATETIME      CONSTRAINT [DF_RP_Base_CheckedOn] DEFAULT (NULL) NULL,
    [ApprovalTo]    INT           CONSTRAINT [DF_RP_Base_ApprovalTo] DEFAULT ((0)) NOT NULL,
    [IsApproved]    INT           CONSTRAINT [DF_RP_Base_IsApproved] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]    VARCHAR (50)  NULL,
    [ApprovedOn]    DATETIME      CONSTRAINT [DF_RP_Base_ApprovedOn] DEFAULT (NULL) NULL,
    [IsReleased]    INT           CONSTRAINT [DF_RP_Base_IsReleased] DEFAULT ((0)) NOT NULL,
    [ReleasedBy]    VARCHAR (50)  NULL,
    [ReleasedOn]    DATETIME      CONSTRAINT [DF_RP_Base_ReleasedOn] DEFAULT (NULL) NULL,
    [DateCreated]   DATETIME      CONSTRAINT [DF__RP_Base__DateCre__2A16A4C8] DEFAULT (getdate()) NULL,
    [CreatedById]   INT           NULL,
    [LastSaved]     DATETIME      NULL,
    [LastSavedById] INT           NULL,
    [Priority]      VARCHAR (50)  CONSTRAINT [DF_RP_Base_Priority] DEFAULT ('Normal') NULL,
    [IsActive]      INT           CONSTRAINT [DF_RP_Base_IsActive] DEFAULT ((1)) NOT NULL,
    [ConnectRelNo]  VARCHAR (150) NULL,
    [WorkOrder]     VARCHAR (150) NULL,
    CONSTRAINT [PK_RP_Base] PRIMARY KEY CLUSTERED ([RelNo] ASC)
);

