CREATE TABLE [dbo].[ShippingBase] (
    [InvoiceNo]       VARCHAR (50)  NOT NULL,
    [DateCreated]     DATETIME      NULL,
    [CreatedBy]       VARCHAR (30)  NULL,
    [DateLastSaved]   DATETIME      NULL,
    [LastSavedBy]     VARCHAR (30)  NULL,
    [JobNumber]       VARCHAR (150) NULL,
    [SalesPerson]     VARCHAR (30)  NULL,
    [Requistioner]    VARCHAR (30)  NULL,
    [Carrier]         VARCHAR (50)  NULL,
    [Collect_Prepaid] INT           NULL,
    [FobPoint]        VARCHAR (25)  NULL,
    [Terms]           VARCHAR (25)  NULL,
    [Currency]        NCHAR (10)    NULL,
    [Total]           MONEY         NULL,
    [Vendor_Cust]     INT           NULL,
    [SoldTo]          VARCHAR (8)   NULL,
    [ShipTo]          VARCHAR (8)   NULL,
    [Notes]           VARCHAR (MAX) NULL,
    [CarrierCode]     VARCHAR (50)  NULL,
    [IsSubmitted]     INT           CONSTRAINT [DF_ShippingBase_IsSubmitted] DEFAULT ((0)) NOT NULL,
    [SubmittedBy]     VARCHAR (50)  NULL,
    [SubmittedOn]     DATETIME      NULL,
    [SubmittedTo]     INT           CONSTRAINT [DF_ShippingBase_SubmittedTo] DEFAULT ((0)) NOT NULL,
    [IsApproved]      INT           CONSTRAINT [DF_ShippingBase_IsApproved] DEFAULT ((0)) NOT NULL,
    [ApprovedBy]      VARCHAR (50)  NULL,
    [ApprovedOn]      DATETIME      NULL,
    [IsShipped]       INT           CONSTRAINT [DF_ShippingBase_IsShipped] DEFAULT ((0)) NOT NULL,
    [ShippedBy]       VARCHAR (50)  NULL,
    [ShippedOn]       DATETIME      NULL,
    CONSTRAINT [PK_ShippingBase] PRIMARY KEY CLUSTERED ([InvoiceNo] ASC)
);

