//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SearchDataSPM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseReq
    {
        public int ID { get; set; }
        public int ReqNumber { get; set; }
        public Nullable<int> OrderId { get; set; }
        public string Item { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Description { get; set; }
        public string Manufacturer { get; set; }
        public string OEMItemNumber { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Notes { get; set; }
    }
}
