CREATE TABLE [dbo].[Opportunities] (
    [ID]                      INT            IDENTITY (1, 1) NOT NULL,
    [Opportunity ID]          INT            NULL,
    [Quote]                   NVARCHAR (50)  NOT NULL,
    [Quote_Date]              DATE           NULL,
    [Customer]                NVARCHAR (50)  NULL,
    [Company_Name]            NVARCHAR (50)  NULL,
    [Title]                   VARCHAR (MAX)  NULL,
    [Description]             VARCHAR (MAX)  NULL,
    [Employee]                NVARCHAR (100) NULL,
    [Category]                NVARCHAR (50)  NULL,
    [Sub_Category]            NVARCHAR (50)  NULL,
    [Rating]                  NVARCHAR (50)  NULL,
    [How_Found]               NVARCHAR (50)  NULL,
    [Open_Date]               DATETIME2 (7)  NULL,
    [Est_Closed_Date]         DATETIME2 (7)  NULL,
    [Probability]             FLOAT (53)     NULL,
    [Est_Revenue]             NVARCHAR (50)  NULL,
    [Currency]                NVARCHAR (50)  NULL,
    [Exchange_Rate]           FLOAT (53)     NULL,
    [Closed]                  INT            NULL,
    [Comments]                NVARCHAR (MAX) NULL,
    [Part_Name]               NVARCHAR (100) NULL,
    [Part_Number]             NVARCHAR (50)  NULL,
    [Engineering_Level]       NVARCHAR (50)  NULL,
    [Part_Type]               NVARCHAR (50)  NULL,
    [Part_Variations]         NVARCHAR (150) NULL,
    [OEM_Name]                NVARCHAR (50)  NULL,
    [Timing]                  NVARCHAR (50)  NULL,
    [Est_Order_Date]          DATETIME2 (7)  NULL,
    [Est_Acceptance_Run_Date] NVARCHAR (50)  NULL,
    [Est_Installation_Date]   NVARCHAR (50)  NULL,
    [Status]                  NVARCHAR (50)  NULL,
    [RfQ_Date]                NVARCHAR (1)   NULL,
    [RfQ_Name]                NVARCHAR (50)  NULL,
    [RfQ_Revision]            NVARCHAR (50)  NULL,
    [RfQ_Received_Date]       DATETIME2 (7)  NULL,
    [RfQ_Document]            NVARCHAR (300) NULL,
    [RfQ_Doc_Date]            NVARCHAR (50)  NULL,
    [RfQ_Drawings]            NVARCHAR (150) NULL,
    [Calculated_Price]        NVARCHAR (50)  NULL,
    [Calculation]             NVARCHAR (100) NULL,
    [Quote_Document]          NVARCHAR (150) NULL,
    [Converted_to_Job]        INT            NULL,
    [Supplier_Number]         NVARCHAR (1)   NULL,
    [Supplier]                NVARCHAR (1)   NULL,
    [LastSavedby]             NVARCHAR (100) NULL,
    [Lastsaved]               DATETIME       NULL,
    [DateCreated]             DATETIME       NULL,
    [FolderPath]              NVARCHAR (500) NULL,
    CONSTRAINT [PK_Opportunities] PRIMARY KEY CLUSTERED ([Quote] ASC)
);

