CREATE TABLE [dbo].[Users] (
    [Emp_Id]               INT            NOT NULL,
    [UserName]             NVARCHAR (50)  NOT NULL,
    [Department]           NVARCHAR (50)  NOT NULL,
    [Name]                 NVARCHAR (50)  NULL,
    [ActiveBlockNumber]    NVARCHAR (50)  NULL,
    [Admin]                INT            CONSTRAINT [DF_Users_Admin] DEFAULT ((0)) NOT NULL,
    [Developer]            INT            CONSTRAINT [DF_Users_Developer] DEFAULT ((0)) NOT NULL,
    [Management]           INT            CONSTRAINT [DF_Users_Management] DEFAULT ((0)) NOT NULL,
    [Quote]                INT            CONSTRAINT [DF_Users_Quote] DEFAULT ((0)) NOT NULL,
    [PurchaseReq]          INT            CONSTRAINT [DF_Users_PurchaseReq] DEFAULT ((0)) NOT NULL,
    [PurchaseReqApproval]  INT            CONSTRAINT [DF_Users_PurchaseReqApproval] DEFAULT ((0)) NOT NULL,
    [PurchaseReqApproval2] INT            CONSTRAINT [DF_Users_PurchaseReqApproval2] DEFAULT ((0)) NOT NULL,
    [PurchaseReqBuyer]     INT            CONSTRAINT [DF_Users_PurchaseReqBuyer] DEFAULT ((0)) NOT NULL,
    [PriceRight]           INT            CONSTRAINT [DF_Users_PriceRight] DEFAULT ((0)) NOT NULL,
    [Shipping]             INT            CONSTRAINT [DF_Users_Shipping] DEFAULT ((0)) NOT NULL,
    [WOScan]               INT            CONSTRAINT [DF_Users_ScanWo] DEFAULT ((0)) NOT NULL,
    [CribCheckout]         INT            CONSTRAINT [DF_Users_CribCheckout] DEFAULT ((0)) NOT NULL,
    [CribShort]            INT            CONSTRAINT [DF_Users_CribShort] DEFAULT ((0)) NOT NULL,
    [ECR]                  INT            CONSTRAINT [DF_Users_PurchaseReq1] DEFAULT ((0)) NOT NULL,
    [ECRApproval]          INT            CONSTRAINT [DF_Users_PurchaseReqApproval1] DEFAULT ((0)) NOT NULL,
    [ECRApproval2]         INT            CONSTRAINT [DF_Users_PurchaseReqApproval21] DEFAULT ((0)) NOT NULL,
    [ECRHandler]           INT            CONSTRAINT [DF_Users_PurchaseReqBuyer1] DEFAULT ((0)) NOT NULL,
    [ECRSup]               INT            CONSTRAINT [DF_Users_ECRSup] DEFAULT ((0)) NOT NULL,
    [ItemDependencies]     INT            CONSTRAINT [DF_Users_ItmDependencies] DEFAULT ((0)) NOT NULL,
    [WORelease]            INT            CONSTRAINT [DF_Users_ReleaseLog] DEFAULT ((0)) NOT NULL,
    [ShipSupervisor]       INT            CONSTRAINT [DF_Users_ShippingManager] DEFAULT ((0)) NOT NULL,
    [ShipSup]              INT            CONSTRAINT [DF_Users_ShipSup] DEFAULT ((0)) NOT NULL,
    [ShippingManager]      INT            CONSTRAINT [DF_Users_Shipper] DEFAULT ((0)) NOT NULL,
    [CheckDrawing]         INT            CONSTRAINT [DF_Users_CheckDrawing] DEFAULT ((0)) NOT NULL,
    [ApproveDrawing]       INT            CONSTRAINT [DF_Users_ApproveDrawing] DEFAULT ((0)) NOT NULL,
    [Supervisor]           INT            NULL,
    [Email]                VARCHAR (100)  NULL,
    [SharesFolder]         NVARCHAR (250) NULL,
    [ReadWhatsNew]         INT            CONSTRAINT [DF_Users_ReadWhatsNew] DEFAULT ((0)) NOT NULL,
    [id]                   INT            IDENTITY (1, 1) NOT NULL,
    CONSTRAINT [PK_Users_1] PRIMARY KEY CLUSTERED ([id] ASC)
);

