CREATE LOGIN [SPM_Agent]
    WITH PASSWORD = N'iuSc$sx.r{c=i=Ch pogfnqsmsFT7_&#$!~<}sRucXxngvrn', SID = 0x069C60962DFF8A4DBCCAA00ED348DB00, DEFAULT_DATABASE = [SPM_Database], DEFAULT_LANGUAGE = [us_english];

